    <?$APPLICATION->IncludeComponent(
        "bitrix:iblock.element.add.form",
        "question",
        Array(
            "USE_EXTENDED_ERRORS" => "Y",
            "CUSTOM_TITLE_DATE_ACTIVE_FROM" => "",
            "CUSTOM_TITLE_DATE_ACTIVE_TO" => "",
            "CUSTOM_TITLE_DETAIL_PICTURE" => "",
            "CUSTOM_TITLE_DETAIL_TEXT" => "",
            "CUSTOM_TITLE_IBLOCK_SECTION" => "",
            "CUSTOM_TITLE_NAME" => "Укажите ваш E-mail",
            "CUSTOM_TITLE_CODE" => "E-mail",
            "CUSTOM_TITLE_PREVIEW_PICTURE" => "Фото",
            "CUSTOM_TITLE_PREVIEW_TEXT" => "Сообщение",
            "CUSTOM_TITLE_TAGS" => "",
            "DEFAULT_INPUT_SIZE" => "30",
            "DETAIL_TEXT_USE_HTML_EDITOR" => "N",
            "ELEMENT_ASSOC" => "CREATED_BY",
            "GROUPS" => [0=>"2"],
            "IBLOCK_ID" => IB_QUESTION_FORM_ID,
            "IBLOCK_TYPE" => "forms",
            "LEVEL_LAST" => "Y",
            "LIST_URL" => "",
            "MAX_FILE_SIZE" => "0",
            "MAX_LEVELS" => "100000",
            "MAX_USER_ENTRIES" => "100",
            "PREVIEW_TEXT_USE_HTML_EDITOR" => "N",
            "PROPERTY_CODES" => ["NAME", "CODE", 54, 56],
            "PROPERTY_CODES_REQUIRED" => ["NAME", "CODE", 54, 56],
            "RESIZE_IMAGES" => "N",
            "SEF_MODE" => "N",
            "STATUS" => "ANY",
            "STATUS_NEW" => "N",
            "USER_MESSAGE_ADD" => "",
            "USER_MESSAGE_EDIT" => "",
            "USE_CAPTCHA" => "N",
            "AJAX_MODE" => "Y",
            "AJAX_OPTION_JUMP"  => "N"
            )
    );?>